# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  TEST_USER_EMAIL : preparation@examname.com
  TEST_USER_PASSWORD : exampassword
  BASE_URL_USED : http://softuni-qa-loadbalancer-2137572849.eu-north-1.elb.amazonaws.com:84
  AUTHENTICATION_STATIC_TOKEN : eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJKd3RTZXJ2aWNlQWNjZXNzVG9rZW4iLCJqdGkiOiI0ZWU1MGJmZC1kYzI4LTQ5MzMtOGYzNS0xMjU2MGE3NjE4ZDIiLCJpYXQiOiIwOC8xMi8yMDI1IDE5OjI1OjU4IiwiVXNlcklkIjoiY2FiMGM0MmYtNjNiYi00ODZiLWQyOGYtMDhkZGQ0ZTA4YmQ4IiwiRW1haWwiOiJwcmVwYXJhdGlvbkBleGFtbmFtZS5jb20iLCJVc2VyTmFtZSI6ImV4YW1wcmVwTmFtZSIsImV4cCI6MTc1NTA0ODM1OCwiaXNzIjoiSWRlYUNlbnRlcl9BcHBfU29mdFVuaSIsImF1ZCI6IklkZWFDZW50ZXJfV2ViQVBJX1NvZnRVbmkifQ.y6y6ehrw3cXzrfRB9OLk7lPA0VERrsrop3yd8D9s3hY

jobs:
               checkout the repo:

               runs-on: ubuntu-latest

               steps:
       
               -name : Checkout code
               uses: actions/checkout@v4

           
                install the needed SDK:
            
                  runs-on: ubuntu-latest

                  steps:
     
                  - name: Setup .NET
                    uses: actions/setup-dotnet@v4
                    with:
                    dotnet-version: 8.0.x


                  restore dependencies:
 
                   runs-on: ubuntu-latest

                   steps:
      
                   - name: Restore dependencies
                  run: dotnet restore 
   
               build:

                runs-on: ubuntu-latest

                steps:
           
                - name : Build
                  run : dotnet build --configuration Release --no-restore

                  test:

                runs-on: ubuntu-latest

                steps:
           
                - name : Test
                  run : dotnet test --configuration Release --no-build
